language: cpp

matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx

dist: xenial

addons:
  apt:
    packages:
    - cmake
    - libeigen3-dev
    - xorg-dev
    - libglu1-mesa-dev
  homebrew:
    packages:
    - cmake
    - eigen

script:
  - cmake -DBIGGER_EXAMPLES=ON . && make
